// ============================================================
//  IMAGE MAP — generado automaticamente
//  Mapea nombre de lugar -> imagen local unica en img/places/
//  Tiene prioridad sobre WIKI_ARTICLES.
// ============================================================

window.IMAGE_MAP = {
  'Aldea de Viet Hai (día 2)': 'img/places/aldea_viet_hai.jpg',
  'Amanecer en Angkor Wat (2º día)': 'img/places/amanecer_en_angkor_wat_2º_día.jpg',
  'Amok': 'img/places/amok.jpg',
  'Amok de pollo o verduras (cena en Pub Street)': 'img/places/fish_amok.jpg',
  'Bahía de Lan Ha': 'img/places/bahía_de_lan_ha.jpg',
  'Bahía de Lan Ha — crucero 2D/1N': 'img/places/bahía_de_lan_ha_crucero_2d_1n.jpg',
  'Bai Sach Chrouk (cerdo a la brasa, desayuno de Phnom Penh)': 'img/places/bai_sach_chrouk.jpg',
  'Banquete a bordo del crucero (incluido)': 'img/places/trang_an.jpg',
  'Beng Mealea': 'img/places/beng_mealea.jpg',
  'Bánh Khoái (crepe crujiente de Hue)': 'img/places/banh_khoai_crepe_hue.jpg',
  'Bánh Mì Phượng (el mejor Bánh Mì del mundo, en Hoi An)': 'img/places/bánh_mì_phượng_el_mejor_bánh_mì_del_mundo_en_hoi_an.jpg',
  'Bánh Mì Phượng (para el camino a la playa)': 'img/places/bánh_mì_phượng_para_el_camino_a_la_playa.jpg',
  'Bánh Mì de viaje en tren': 'img/places/banh_mi_viaje_tren.jpg',
  'Bánh Xèo (crepe crocante vietnamita)': 'img/places/bánh_xèo_crepe_crocante_vietnamita.jpg',
  'Bún Bò Huế (sopa picante de Hue)': 'img/places/bún_bò_huế_sopa_picante_de_hue.jpg',
  'Bún Chả Hương Liên': 'img/places/bún_chả_hương_liên.jpg',
  'Bún chả Hương Liên': 'img/places/bún_chả_hương_liên.jpg',
  'Café Giang (Café de Huevo)': 'img/places/café_giang_café_de_huevo.jpg',
  'Café Phố Cổ (azotea secreta sobre el lago)': 'img/places/café_phố_cổ_azotea_secreta_sobre_el_lago.jpg',
  'Café de azotea sobre el Lago Hoan Kiem': 'img/places/cafe_azotea_hoan_kiem.jpg',
  'Calle Trần Phú — azoteas y Mot Hoi An': 'img/places/calle_tran_phu_hoi_an.jpg',
  'Calle del Incienso de Thuy Xuan': 'img/places/calle_del_incienso_de_thuy_xuan.jpg',
  'Cao Lau': 'img/places/cao_lau.jpg',
  'Cao Lau Thanh': 'img/places/japanese_covered_bridge.jpg',
  'Casco Antiguo — Bono Old Quarter': 'img/places/casco_antiguo_hoi_an.jpg',
  'Catedral de San José': 'img/places/catedral_san_jose_hanoi.jpg',
  'Cementerio City of Ghosts (Đàn Nam Giao)': 'img/places/cementerio_city_of_ghosts_đàn_nam_giao.jpg',
  'Cena a la luz de las velas en la playa': 'img/places/cena_velas_playa_koh_rong.jpg',
  'Cena jemer junto al Mekong (última en Camboya)': 'img/places/cena_jemer_mekong.jpg',
  'Cena ligera antes del bus nocturno': 'img/places/cena_ligera_bus_nocturno.jpg',
  'Central Market (Phsar Thmei)': 'img/places/central_market_phnom_penh.jpg',
  'Chả Cá Lã Vọng (el único plato del restaurante más antiguo de Hanói)': 'img/places/chả_cá_lã_vọng_el_único_plato_del_restaurante_más_antiguo_de_hanói.jpg',
  'Clase de cocina en isla Thuan Tinh': 'img/places/clase_cocina_thuan_tinh.jpg',
  'Comida post-trekking (bar de playa)': 'img/places/comida_post_trekking_bar_playa.jpg',
  'Compras en el Old Quarter': 'img/places/compras_old_quarter_hanoi.jpg',
  'Cueva Trung Trang': 'img/places/cueva_trung_trang.jpg',
  'Cuevas de Lan Ha': 'img/places/cuevas_de_lan_ha.jpg',
  'Cà Phê Trứng': 'img/places/cà_phê_trứng.jpg',
  'Cơm Gà Bà Buội (arroz con pollo)': 'img/places/com_ga_ba_buoi.jpg',
  'Cơm Hến (arroz con almejas de Hue)': 'img/places/cơm_hến_arroz_con_almejas_de_hue.jpg',
  'Fish Amok': 'img/places/fish_amok.jpg',
  'Fish Amok (curry jemer en hoja de coco)': 'img/places/cambodian_cuisine.jpg',
  'Hang Mua': 'img/places/hang_mua.jpg',
  'Ho Thuy Tien (Parque abandonado)': 'img/places/ho_thuy_tien_parque_abandonado.jpg',
  'Hoi An Memories Show': 'img/places/hoi_an_memories_show.jpg',
  'Kayak en cuevas de Lan Ha': 'img/places/kayak_cuevas_lan_ha.jpg',
  'Khmer BBQ (última noche en Siem Reap)': 'img/places/khmer_bbq.jpg',
  'Killing Fields de Choeung Ek': 'img/places/killing_fields_de_choeung_ek.jpg',
  'Koh Rong Sanloem': 'img/places/koh_rong_sanloem.jpg',
  'Lago Hoan Kiem': 'img/places/lago_hoan_kiem.jpg',
  'Lago Hoan Kiem (despedida)': 'img/places/lago_hoan_kiem_despedida.jpg',
  'Lan Ha Bay': 'img/places/lan_ha_bay.jpg',
  'Lan Ha Sky Bar — Flamingo Resort': 'img/places/lan_ha_sky_bar_flamingo_resort.jpg',
  'Lap Khmer (ceviche camboyano de ternera)': 'img/places/lap_khmer_ceviche_camboyano_de_ternera.jpg',
  'Lazy Beach': 'img/places/lazy_beach.jpg',
  'Le Pain Du Coeur': 'img/places/le_pain_du_coeur.jpg',
  'Lok Lak (ternera salteada camboyana)': 'img/places/lok_lak_ternera_salteada_camboyana.jpg',
  'M\'Pai Bay (pueblo local)': 'img/places/mpai_bay_koh_rong.jpg',
  'Marble Mountains': 'img/places/marble_mountains.jpg',
  'Mariscos frescos a la brasa (Saracen Bay)': 'img/places/mariscos_frescos_a_la_brasa_saracen_bay.jpg',
  'Mariscos frescos del puerto de Cat Ba': 'img/places/mariscos_frescos_cat_ba.jpg',
  'Mercado Ruso (Tuol Tom Poung)': 'img/places/russian_market.jpg',
  'Mercado de Angkor Night Market': 'img/places/mercado_de_angkor_night_market.jpg',
  'Mercados de Hoi An': 'img/places/mercados_de_hoi_an.jpg',
  'Miradores de Cat Ba': 'img/places/mua_cave.jpg',
  'Museo del Genocidio Tuol Sleng (S-21)': 'img/places/museo_del_genocidio_tuol_sleng_s_21.jpg',
  'Mì Quảng (fideos de cúrcuma, plato del Centro)': 'img/places/mì_quảng_fideos_de_cúrcuma_plato_del_centro.jpg',
  'Mì Quảng o Cao Lầu (primer plato de Hoi An)': 'img/places/cao_lau_hoi_an.jpg',
  'Ngu Lam Peak (mirador alternativo)': 'img/places/ngu_lam_peak.jpg',
  'Nom Banh Chok (desayuno ligero antes del S-21)': 'img/places/nom_banh_chok_desayuno_ligero_antes_del_s_21.jpg',
  'Num Banh Chok (fideos jemer al amanecer)': 'img/places/num_banh_chok_fideos_jemer_al_amanecer.jpg',
  'Old Quarter': 'img/places/old_quarter.jpg',
  'Old Town Hoi An': 'img/places/old_town_hoi_an.jpg',
  'Orillas del Mekong': 'img/places/orillas_del_mekong.jpg',
  'Pagodas de Hue': 'img/places/pagodas_de_hue.jpg',
  'Parque Nacional Cat Ba': 'img/places/parque_nacional_cat_ba.jpg',
  'Parque Nacional de Cuc Phuong (opcional)': 'img/places/parque_nacional_cuc_phuong.jpg',
  'Pho Thin': 'img/places/pho_thin.jpg',
  'Phở Bò': 'img/places/phở_bò.jpg',
  'Phở Gà o Phở Bò (desayuno de reencuentro con Vietnam)': 'img/places/pho_ga_pho_bo_desayuno_vietnam.jpg',
  'Phở o Bún Bò Nam Bộ (cocina vietnamita del norte)': 'img/places/phở_o_bún_bò_nam_bộ_cocina_vietnamita_del_norte.jpg',
  'Playa An Bang': 'img/places/playa_an_bang.jpg',
  'Playa principal': 'img/places/playa_principal.jpg',
  'Playa salvaje de Tung Thu': 'img/places/playa_salvaje_tung_thu.jpg',
  'Prisión Hoa Lo (Hanoi Hilton)': 'img/places/prision_hoa_lo.jpg',
  'Pub Street': 'img/places/pub_street.jpg',
  'Pub Street y Old Market': 'img/places/pub_street_y_old_market.jpg',
  'Puente Cubierto Japonés (Chua Cau)': 'img/places/puente_cubierto_japonés_chua_cau.jpg',
  'Puente del Dragón': 'img/places/puente_del_dragón.jpg',
  'Restaurante junto al Mekong': 'img/places/restaurante_junto_al_mekong.jpg',
  'Ruta de playas Cat Co (1, 2 y 3)': 'img/places/ruta_playas_cat_co.jpg',
  'Ruta en bici isla de Cam Kim': 'img/places/ruta_en_bici_isla_de_cam_kim.jpg',
  'Río Perfume': 'img/places/río_perfume.jpg',
  'Sampán por Tam Coc (3 cuevas)': 'img/places/sampán_por_tam_coc_3_cuevas.jpg',
  'Santuario de My Son': 'img/places/santuario_de_my_son.jpg',
  'Street food Old Quarter': 'img/places/vietnamese_cuisine.jpg',
  'Ta Prohm': 'img/places/ta_prohm.jpg',
  'Talleres artesanales Hoi An': 'img/places/talleres_artesanales_hoi_an.jpg',
  'Tam Coc': 'img/places/tam_coc.jpg',
  'Templo de la Literatura': 'img/places/templo_de_la_literatura.jpg',
  'Templos a elegir': 'img/places/templos_a_elegir.jpg',
  'The Note Coffee': 'img/places/the_note_coffee.jpg',
  'Trang An': 'img/places/trang_an.jpg',
  'Trekking al Faro Militar (la más épica)': 'img/places/trekking_faro_militar_koh_rong.jpg',
  'Tren callejero (Train Street)': 'img/places/tren_callejero_train_street.jpg',
  'Tren callejero de Hanói': 'img/places/tren_callejero_de_hanói.jpg',
  'White Rose (B\u00e1nh Bao V\u1ea1c)': 'img/places/white_rose_banh_bao_vac.jpg',
  'White Rose (Bánh Bao Vạc)': 'img/places/white_rose_banh_bao_vac.jpg',
  'White Rose Restaurant': 'img/places/white_rose_restaurant.jpg',
  'Ópera de Hanói': 'img/places/ópera_de_hanói.jpg',
  'Última mañana en el Old Town': 'img/places/ultima_manana_hoi_an.jpg',
  'Última ruta de street food': 'img/places/ultima_ruta_street_food_hanoi.jpg',
  'Último Phở o Bánh Mì antes del vuelo': 'img/places/último_phở_o_bánh_mì_antes_del_vuelo.jpg',
  'Último desayuno vietnamita (Hoi An)': 'img/places/último_desayuno_vietnamita_hoi_an.jpg',
  'Último paseo — Old Quarter al amanecer': 'img/places/old_quarter_amanecer.jpg',
};
